# Generated by Django 5.0 on 2023-12-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.IntegerField()),
                ('t_name', models.CharField(default='', max_length=10)),
                ('w_name', models.CharField(default='', max_length=10)),
                ('pda', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
